// Only fictional contacts and an isolated in-memory DB; no real phone call or push.
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { appendFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { testDatabase } from './test-db.mjs';
import { coachTestEnvironment } from './coach-test-env.mjs';
import { createSession, authCookieName } from '../lib/session.ts';

const fixture = await testDatabase(0, 50);
const db = fixture.client;
const output = new URL('../test-results/emil/', import.meta.url);
await mkdir(output, { recursive: true });
process.env.SESSION_SECRET = randomBytes(32).toString('hex');
const port = Number(process.env.COACH_TEST_PORT || 3118);
const origin = `http://localhost:${port}`;
const production = process.env.CRM_TEST_PRODUCTION === '1';
const server = spawn(process.execPath, ['node_modules/next/dist/bin/next', production ? 'start' : 'dev', '-p', String(port), '--hostname', '127.0.0.1'], { env: await coachTestEnvironment(fixture.url, process.env.SESSION_SECRET), windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
let log = ''; const logChunk = c => { log += c; appendFileSync(new URL('live.log', output), c); }; server.stdout.on('data', logChunk); server.stderr.on('data', logChunk);
let browser, page, failed = false;
try {
  await db.feature.update({ where: { key: 'miniEmil' }, data: { state: 'TEST' } });
  for (let i = 0; i < 90; i++) {
    try { if ((await fetch(`${origin}/login`, { signal: AbortSignal.timeout(15000) })).ok) break; } catch {}
    if (server.exitCode !== null || log.includes('Module not found:') || i === 89) throw new Error(`Server unavailable: ${log.slice(-3000)}`);
    await new Promise(resolve => setTimeout(resolve, 500));
  }
  browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce', serviceWorkers: 'block' });
  const user = await db.user.create({ data: { name: 'Emil Browser', onboardingDoneAt: new Date(), startTrack: 'VERKAUF', person: { create: { name: 'Emil Browser' } }, startProgress: { create: { phase: 'COLLECTION', kind: 'VERKAUF' } } } });
  await context.addCookies([{ name: authCookieName, value: await createSession(user.id), url: origin }]);
  page = await context.newPage(); page.setDefaultTimeout(45000);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const screenshot = name => page.screenshot({ path: fileURLToPath(new URL(name, output)), fullPage: false });
  const state = () => db.startProgress.findUniqueOrThrow({ where: { userId: user.id } });
  const coach = page.getByRole('complementary', { name: 'Mini-Emil Begleitung' });

  await page.goto(`${origin}/start`);
  await page.waitForURL('**/namen/sammeln?**');
  await coach.getByRole('heading', { name: 'Ein Name nach dem anderen.' }).waitFor();
  await page.waitForFunction(() => [...document.querySelectorAll('.emil-dock img')].every(img => img.complete && img.naturalWidth > 0));
  await screenshot('01-collection-mobile-dark.png');
  assert.equal(await db.contact.count({ where: { ownerId: user.id } }), 0, 'Animation must not save its example');
  await coach.getByRole('button', { name: 'Nächstes Bild' }).click();
  await page.setViewportSize({ width: 320, height: 568 });
  await screenshot('02-collection-small.png');
  const bounds = await coach.evaluate(el => ({ right: el.getBoundingClientRect().right, bottom: el.getBoundingClientRect().bottom, width: innerWidth, navTop: document.querySelector('.crm-dock').getBoundingClientRect().top }));
  assert.ok(bounds.right <= bounds.width && bounds.bottom <= bounds.navTop, 'Coach must leave navigation accessible');
  await coach.getByRole('button', { name: 'Jetzt selbst machen' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Anna Probe');
  await coach.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Hinzufügen', exact: true }).click();
  await page.getByText('Gespeichert. Du kannst direkt den nächsten Namen eingeben.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Für heute fertig', exact: true }).click();
  await page.getByRole('link', { name: 'Nummern ergänzen', exact: true }).click();
  await coach.getByRole('heading', { name: 'Jetzt wird’s erreichbar.' }).waitFor();
  await coach.getByRole('button', { name: 'Jetzt selbst machen' }).click();
  await page.getByRole('textbox', { name: 'Telefonnummer', exact: true }).fill('0301234567');
  await page.getByRole('button', { name: 'Nummer speichern', exact: true }).click();
  await page.getByRole('button', { name: 'Erste Anrufe vorbereiten', exact: true }).click();
  await coach.getByRole('heading', { name: 'Den ersten Satz hast du schon.' }).waitFor();
  await screenshot('03-call-preview.png');
  await coach.getByRole('button', { name: 'Begleitung pausieren' }).click();
  await page.waitForFunction(() => !document.querySelector('.emil-card'));
  assert.equal((await state()).paused, true);
  await page.goto(`${origin}/start`); await page.waitForURL('**/heute');
  await page.goto(`${origin}/profil?emil=1`);
  await coach.getByRole('button', { name: 'Begleitung fortsetzen' }).click();
  await page.waitForURL('**/namen/anrufen?**');
  assert.equal((await state()).paused, false);
  await page.getByRole('button', { name: 'Nicht erreicht', exact: true }).click();
  await page.getByText('1 Anrufversuch eingetragen.', { exact: true }).waitFor();
  await page.goto(`${origin}/start`); await page.waitForURL('**/heute');
  assert.equal((await state()).phase, 'CALLS');
  const contact = await db.contact.findFirstOrThrow({ where: { ownerId: user.id, name: 'Anna Probe' } });
  await page.goto(`${origin}/namen/anrufen?kontakt=${contact.id}`);
  await page.getByRole('button', { name: 'Termin', exact: true }).click();
  await page.locator('input[type=datetime-local]').fill('2030-01-02T16:00');
  await page.getByRole('button', { name: 'Termin speichern', exact: true }).click();
  await page.getByText('1 Anrufversuch eingetragen.', { exact: true }).waitFor();
  await page.goto(`${origin}/start`); await page.waitForURL('**/heute');
  assert.equal((await state()).phase, 'APPOINTMENT');
  await coach.getByRole('heading', { name: 'Dein Termin hat seinen Platz.' }).waitFor();
  await screenshot('04-future-appointment.png');
  await page.goto('about:blank');
  await db.contact.update({ where: { id: contact.id }, data: { nextStepAt: new Date('2020-01-02'), appointmentAt: new Date('2020-01-02') } });
  await page.goto(`${origin}/contacts/${contact.id}`);
  await coach.getByRole('heading', { name: 'Was kam raus – und wer noch?' }).waitFor();
  await coach.getByRole('button', { name: 'Jetzt selbst machen' }).click();
  await page.getByRole('button', { name: 'Gehalten', exact: true }).click();
  await coach.waitFor({ state: 'hidden' });
  await page.getByRole('dialog', { name: 'Termin gehalten' }).getByRole('button', { name: 'Kein Abschluss', exact: true }).click();
  await page.getByRole('dialog', { name: 'Termin gehalten' }).waitFor({ state: 'hidden' });
  await page.goto(`${origin}/heute`);
  await coach.getByRole('heading', { name: 'Die erste Runde steht.' }).waitFor();
  assert.equal((await state()).phase, 'DONE');
  await screenshot('05-complete.png');
  await coach.getByRole('button', { name: 'Emil einklappen' }).click();
  await page.reload();
  await coach.getByRole('button', { name: 'Emil, hilf mir', exact: true }).waitFor();
  assert.equal(await coach.locator('.emil-card').count(), 0, 'Completed round is on demand, no repeated demo');
  await coach.getByRole('button', { name: 'Emil, hilf mir', exact: true }).click();
  await coach.getByRole('button', { name: 'Einheiten', exact: false }).click();
  await coach.getByRole('heading', { name: 'Jetzt stehen auch die Einheiten.' }).waitFor();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(() => document.documentElement.classList.remove('dark'));
  await screenshot('06-help-desktop-light.png');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await coach.getByRole('button', { name: 'Pause', exact: true }).waitFor();
  await coach.getByRole('button', { name: 'Pause', exact: true }).click();
  assert.equal(await db.einheitenbuchung.count({ where: { userId: user.id } }), 0, 'Units preview is read-only');

  // A second real UI round: defer units, resume the reminder, then book the linked amount.
  await page.goto('about:blank');
  const winner = await db.user.create({ data: { name: 'Emil Abschlussprobe', onboardingDoneAt: new Date(), startTrack: 'VERKAUF', person: { create: { name: 'Emil Abschlussprobe' } }, startProgress: { create: { version: 2, phase: 'RESULT', kind: 'VERKAUF', coachSeen: ['names', 'phone', 'call', 'appointment', 'result'] } } } });
  const wonContact = await db.contact.create({ data: { ownerId: winner.id, name: 'Ben Abschlussprobe', phone: '0301234567', listKinds: ['VERKAUF'], stage: 'TERMIN_VEREINBART', nextStepType: 'TERMIN', nextStepAt: new Date('2020-01-02'), appointmentAt: new Date('2020-01-02') } });
  await context.addCookies([{ name: authCookieName, value: await createSession(winner.id), url: origin }]);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto(`${origin}/contacts/${wonContact.id}`);
  await page.getByRole('button', { name: 'Gehalten', exact: true }).click();
  await page.getByRole('dialog', { name: 'Termin gehalten' }).getByRole('button', { name: 'Abschluss', exact: true }).click();
  const unitsDialog = page.getByRole('dialog', { name: 'Abschluss steht' });
  await unitsDialog.getByRole('button', { name: 'Später', exact: true }).click();
  await unitsDialog.waitFor({ state: 'hidden' });
  await page.goto(`${origin}/heute`);
  await coach.getByRole('heading', { name: 'Jetzt stehen auch die Einheiten.' }).waitFor();
  assert.equal((await db.startProgress.findUniqueOrThrow({ where: { userId: winner.id } })).phase, 'UNITS', 'Deferring units keeps the round open');
  await screenshot('07-units-still-open.png');
  await coach.getByRole('button', { name: 'Jetzt selbst machen' }).click();
  await page.waitForURL('**/fortschritt/einheiten-offen');
  await page.getByRole('button', { name: 'Eintragen', exact: true }).click();
  await unitsDialog.getByRole('textbox', { name: 'Einheiten', exact: true }).fill('12,50');
  await unitsDialog.getByRole('button', { name: 'Eintragen', exact: true }).click();
  await page.getByRole('dialog', { name: 'Einheiten eingetragen' }).getByRole('button', { name: 'Weiter', exact: true }).click();
  await page.goto(`${origin}/heute`);
  await coach.getByRole('heading', { name: 'Die erste Runde steht.' }).waitFor();
  assert.equal((await db.startProgress.findUniqueOrThrow({ where: { userId: winner.id } })).phase, 'DONE');
  const linked = await db.einheitenErinnerung.findFirstOrThrow({ where: { userId: winner.id, contactId: wonContact.id } });
  const booking = await db.einheitenbuchung.findUniqueOrThrow({ where: { id: linked.buchungId } });
  assert.equal(booking.hundertstel, 1250);
  assert.equal(await page.locator('summary').filter({ hasText: 'Deine erste Runde' }).count(), 0, 'The legacy checklist must not contradict Emil');
  await screenshot('08-win-round-complete.png');
  await db.feature.update({ where: { key: 'miniEmil' }, data: { state: 'AUS' } });
  await page.reload(); assert.equal(await coach.count(), 0);
  assert.deepEqual(errors, []);
  console.log('PASS: Mini-Emil mobile/320px, reduced motion, real names/phone/call/appointment/result, deferred and linked units, pause/resume, on-demand help, desktop/light, feature off; previews never write CRM data.');
} catch (error) {
  if (page) await page.screenshot({ path: fileURLToPath(new URL('failure.png', output)), fullPage: true }).catch(() => {});
  console.error('Fictional fixture diagnostics:', { url: page?.url(), progress: await db.startProgress.findMany({ select: { phase: true, paused: true, coachSeen: true } }), disabledButtons: page ? await page.locator('button:disabled').allTextContents().catch(() => []) : [] });
  console.error(error); failed = true;
} finally {
  await writeFile(new URL('server.log', output), log);
  await browser?.close();
  if (process.platform === 'win32') { const killer = spawn('taskkill', ['/PID', String(server.pid), '/T', '/F'], { windowsHide: true, stdio: 'ignore' }); await new Promise(resolve => killer.on('exit', resolve)); }
  else server.kill();
  await fixture.close();
}
process.exit(failed ? 1 : 0);
