import assert from "node:assert/strict";
import { vereinbarungMoeglich, vereinbarungSichtbar, naechsterVereinbarungsstand, vereinbarungAenderbar, vereinbarungFaellig } from "../lib/vereinbarungen-regeln.ts";
import { pipelineFreigegeben } from "../lib/einblick-regeln.ts";
import { tagesmeldungenBuendeln } from "../lib/vereinbarungen-meldungen.ts";

const chef = { id: "chef", path: "/chef/", deactivatedAt: null, passwordHash: "test" };
const partner = { ...chef, id: "partner", path: "/chef/partner/" };
const dritter = { ...chef, id: "dritter", path: "/chef/dritter/" };
const stand = { initiatorId: "chef", empfaengerId: "partner", vorgeschlagenVonId: "chef", status: "VORGESCHLAGEN", version: 1 };
assert.equal(vereinbarungMoeglich(chef, partner), true);
assert.equal(vereinbarungMoeglich(partner, chef), true);
assert.equal(vereinbarungMoeglich(partner, dritter), false);
assert.equal(vereinbarungMoeglich(chef, { ...partner, path: "/anderer/partner/" }), false, "Teamwechsel entzieht Zugriff");
assert.equal(vereinbarungMoeglich(chef, { ...partner, deactivatedAt: new Date() }), false);
assert.equal(vereinbarungMoeglich(chef, { ...partner, passwordHash: null }), false);
assert.equal(vereinbarungMoeglich({ ...chef, path: "/" }, partner), false);
assert.equal(vereinbarungSichtbar("dritter", chef, partner), false, "Keine Einsicht durch Unbeteiligte");
assert.equal(naechsterVereinbarungsstand(stand, "chef", 1, "BESTAETIGEN"), null, "Eigene Vorschläge nicht selbst bestätigen");
assert.equal(naechsterVereinbarungsstand(stand, "partner", 1, "BESTAETIGEN"), "BESTAETIGT");
assert.equal(naechsterVereinbarungsstand(stand, "partner", 0, "BESTAETIGEN"), null, "Alte Version nicht bestätigen");
assert.equal(naechsterVereinbarungsstand(stand, "partner", 1, "ERLEDIGEN"), null);
assert.equal(naechsterVereinbarungsstand({ ...stand, status: "BESTAETIGT" }, "partner", 1, "ERLEDIGEN"), "ERLEDIGT");
assert.equal(vereinbarungAenderbar({ ...stand, status: "ERLEDIGT" }, "chef", 1), false);
assert.equal(vereinbarungFaellig("VORGESCHLAGEN", new Date("2026-09-01"), new Date("2026-09-08")), false);
assert.equal(vereinbarungFaellig("BESTAETIGT", new Date("2026-09-01"), new Date("2026-09-08")), true);
assert.equal(pipelineFreigegeben("NAMEN"), true);
assert.equal(pipelineFreigegeben("PIPELINE"), true);
assert.equal(pipelineFreigegeben("ZAHLEN"), false);
const gebuendelt = tagesmeldungenBuendeln([{ titel: "Kundentermin", text: "Um 10 Uhr", url: "/kalender", kennung: "kundentermin" }, { titel: "Absprache", text: "Fällig", url: "/mannschaft", kennung: "team" }]);
assert.equal(gebuendelt.url, "/heute");
assert.ok(gebuendelt.text.includes("Kundentermin"));
assert.ok(gebuendelt.text.includes("Absprache"));
assert.equal(tagesmeldungenBuendeln([]), null);
console.log("Vereinbarungen: Zugriff, Bestätigung, Version, Status, Fälligkeit und Freigaben geprüft.");
